apiVersion: v1
kind: Service
metadata:
  name: health-check-service
  namespace: app
spec:
  selector:
    app: carbond-intl-app-gw
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
